version: '3.7'

services:
  # API GATEWAY
  api-gateway:
    image: io-server/krakend
    container_name: io_server_api_gateway
    restart: always
    build:
      context: .
      dockerfile: ./containers/krakend/Dockerfile
      args:
        - TARGET_KRAKEND_VERSION=${KRAKEND_VERSION}
    networks:
      local-network:
        aliases:
          - api-gateway.${LOCAL_DOMAIN}

  # WEB UI NODE
  web-ui-node:
    image: fastybird/web-ui-node:latest
    container_name: io_server_web_ui_node
    restart: always
    networks:
      local-network:
        aliases:
          - web-ui-node.${LOCAL_DOMAIN}
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 5000
      NUXT_ENV_I18N_LOCALE: en
      NUXT_ENV_I18N_FALLBACK_LOCALE: en
      NUXT_ENV_API_TARGET: http://api-gateway.${LOCAL_DOMAIN}:8000
      NUXT_ENV_API_KEY: ${APP_API_KEY}
      NUXT_ENV_WS_TARGET: ws://websockets-node.${LOCAL_DOMAIN}:9787
      NUXT_ENV_WS_KEY: ${APP_WS_KEY}

  # AUTH NODE
  auth-node:
    image: fastybird/auth-node:latest
    container_name: io_server_accounts_node
    restart: always
    depends_on:
      - mariadb-auth-node
    networks:
      local-network:
        aliases:
          - auth-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__DATABASE_HOST: mariadb-auth-node.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__DATABASE_PORT: ${MYSQL_PORT}
      FB_NODE_PARAMETER__DATABASE_USERNAME: ${MYSQL_USER}
      FB_NODE_PARAMETER__DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      FB_NODE_PARAMETER__SECURITY_SIGNATURE: ${APP_TOKEN_SIGNATURE}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}, mariadb-auth-node.${LOCAL_DOMAIN}:${MYSQL_PORT}

  # DEVICES NODE
  devices-node:
    image: fastybird/devices-node:latest
    container_name: io_server_devices_node
    restart: always
    depends_on:
      - mariadb-devices-node
      - rabbitmq
    networks:
      local-network:
        aliases:
          - devices-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__RABBITMQ_HOST: rabbitmq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__RABBITMQ_PORT: ${RABBIT_MQ_PORT}
      FB_NODE_PARAMETER__RABBITMQ_USERNAME: ${RABBIT_MQ_USER}
      FB_NODE_PARAMETER__RABBITMQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      FB_NODE_PARAMETER__DATABASE_HOST: mariadb-devices-node.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__DATABASE_PORT: ${MYSQL_PORT}
      FB_NODE_PARAMETER__DATABASE_USERNAME: ${MYSQL_USER}
      FB_NODE_PARAMETER__DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      FB_NODE_PARAMETER__SECURITY_SIGNATURE: ${APP_TOKEN_SIGNATURE}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}, mariadb-devices-node.${LOCAL_DOMAIN}:${MYSQL_PORT}

  # MQTT NODE
  mqtt-node:
    image: fastybird/mqtt-node:latest
    container_name: io_server_mqtt_node
    restart: always
    depends_on:
      - vernemq
      - rabbitmq
    networks:
      local-network:
        aliases:
          - mqtt-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__RABBITMQ_HOST: rabbitmq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__RABBITMQ_PORT: ${RABBIT_MQ_PORT}
      FB_NODE_PARAMETER__RABBITMQ_USERNAME: ${RABBIT_MQ_USER}
      FB_NODE_PARAMETER__RABBITMQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      FB_NODE_PARAMETER__MQTT_HOST: vernemq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__MQTT_PORT: ${VERNE_MQ_PORT}
      FB_NODE_PARAMETER__MQTT_USERNAME: ${VERNE_MQ_USER}
      FB_NODE_PARAMETER__MQTT_PASSWORD: ${VERNE_MQ_PASSWORD}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}, vernemq.${LOCAL_DOMAIN}:${VERNE_MQ_PORT}

  # STORAGE NODE
  storage-node:
    image: fastybird/storage-node:latest
    container_name: io_server_storage_node
    restart: always
    depends_on:
      - couchdb
      - rabbitmq
    networks:
      local-network:
        aliases:
          - storage-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__RABBITMQ_HOST: rabbitmq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__RABBITMQ_PORT: ${RABBIT_MQ_PORT}
      FB_NODE_PARAMETER__RABBITMQ_USERNAME: ${RABBIT_MQ_USER}
      FB_NODE_PARAMETER__RABBITMQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      FB_NODE_PARAMETER__COUCHDB_HOST: couchdb.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__COUCHDB_PORT: ${COUCHDB_PORT}
      FB_NODE_PARAMETER__COUCHDB_USERNAME: ${COUCHDB_USER}
      FB_NODE_PARAMETER__COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      FB_NODE_PARAMETER__SECURITY_SIGNATURE: ${APP_TOKEN_SIGNATURE}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}, couchdb.${LOCAL_DOMAIN}:${COUCHDB_PORT}

  # WEBSOCKETS NODE
  websockets-node:
    image: fastybird/websockets-node:latest
    container_name: io_server_websockets_node
    restart: always
    depends_on:
      - rabbitmq
    networks:
      local-network:
        aliases:
          - websockets-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__RABBITMQ_HOST: rabbitmq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__RABBITMQ_PORT: ${RABBIT_MQ_PORT}
      FB_NODE_PARAMETER__RABBITMQ_USERNAME: ${RABBIT_MQ_USER}
      FB_NODE_PARAMETER__RABBITMQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      FB_NODE_PARAMETER__SERVER_KEYS: ${APP_WS_KEY}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}

  # TRIGGERS NODE
  triggers-node:
    image: fastybird/triggers-node:latest
    container_name: io_server_triggers_node
    restart: always
    depends_on:
      - mariadb-triggers-node
      - rabbitmq
    networks:
      local-network:
        aliases:
          - triggers-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__RABBITMQ_HOST: rabbitmq.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__RABBITMQ_PORT: ${RABBIT_MQ_PORT}
      FB_NODE_PARAMETER__RABBITMQ_USERNAME: ${RABBIT_MQ_USER}
      FB_NODE_PARAMETER__RABBITMQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
      FB_NODE_PARAMETER__DATABASE_HOST: mariadb-triggers-node.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__DATABASE_PORT: ${MYSQL_PORT}
      FB_NODE_PARAMETER__DATABASE_USERNAME: ${MYSQL_USER}
      FB_NODE_PARAMETER__DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      FB_NODE_PARAMETER__SECURITY_SIGNATURE: ${APP_TOKEN_SIGNATURE}
      WAIT_HOSTS: rabbitmq.${LOCAL_DOMAIN}:${RABBIT_MQ_PORT}, mariadb-triggers-node.${LOCAL_DOMAIN}:${MYSQL_PORT}

  # UI NODE
  ui-node:
    image: fastybird/ui-node:latest
    container_name: io_server_ui_node
    restart: always
    depends_on:
      - mariadb-ui-node
    networks:
      local-network:
        aliases:
          - ui-node.${LOCAL_DOMAIN}
    environment:
      FB_NODE_PARAMETER__DATABASE_HOST: mariadb-ui-node.${LOCAL_DOMAIN}
      FB_NODE_PARAMETER__DATABASE_PORT: ${MYSQL_PORT}
      FB_NODE_PARAMETER__DATABASE_USERNAME: ${MYSQL_USER}
      FB_NODE_PARAMETER__DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      FB_NODE_PARAMETER__SECURITY_SIGNATURE: ${APP_TOKEN_SIGNATURE}
      WAIT_HOSTS: mariadb-ui-node.${LOCAL_DOMAIN}:${MYSQL_PORT}

  # DATABASE ACCOUNTS NODE CONTAINER
  mariadb-auth-node:
    image: mariadb
    container_name: io_server_mariadb_accounts_node
    restart: always
    volumes:
      # Mount database data folder
      - mariadb_accounts_node_data:/var/lib/mysql
    networks:
      local-network:
        aliases:
          - mariadb-auth-node.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_ACCOUNTS_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  # DATABASE DEVICES NODE CONTAINER
  mariadb-devices-node:
    image: mariadb
    container_name: io_server_mariadb_devices_node
    restart: always
    volumes:
      # Mount database data folder
      - mariadb_devices_node_data:/var/lib/mysql
    networks:
      local-network:
        aliases:
          - mariadb-devices-node.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DEVICES_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  # DATABASE TRIGGERS NODE CONTAINER
  mariadb-triggers-node:
    image: mariadb
    container_name: io_server_mariadb_triggers_node
    restart: always
    volumes:
      # Mount database data folder
      - mariadb_triggers_node_data:/var/lib/mysql
    networks:
      local-network:
        aliases:
          - mariadb-triggers-node.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TRIGGERS_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  # DATABASE UI NODE CONTAINER
  mariadb-ui-node:
    image: mariadb
    container_name: io_server_mariadb_ui_node
    restart: always
    volumes:
      # Mount database data folder
      - mariadb_ui_node_data:/var/lib/mysql
    networks:
      local-network:
        aliases:
          - mariadb-ui-node.${LOCAL_DOMAIN}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_UI_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]

  # DEVICE STATES DATABASE CONTAINER
  couchdb:
    image: io-server/couchdb
    container_name: io_server_couchdb
    restart: always
    build:
      context: .
      dockerfile: ./containers/couchdb/Dockerfile
      args:
        - TARGET_COUCHDB_VERSION=${COUCHDB_VERSION}
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      local-network:
        aliases:
          - couchdb.${LOCAL_DOMAIN}
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}

  # RABBIT MQ DATA EXCHANGE CONTAINER
  rabbitmq:
    image: io-server/rabbitmq
    container_name: io_server_rabbitmq
    restart: always
    build:
      context: .
      dockerfile: ./containers/rabbitmq/Dockerfile
      args:
        - TARGET_RABBIT_MQ_VERSION=${RABBIT_MQ_VERSION}
        - RABBIT_MQ_USER=${RABBIT_MQ_USER}
        - RABBIT_MQ_PASSWORD=${RABBIT_MQ_PASSWORD}
    networks:
      local-network:
        aliases:
          - rabbitmq.${LOCAL_DOMAIN}

  # VERNE MQ CONTAINER
  vernemq:
    image: io-server/vernemq
    container_name: io_server_vernemq
    restart: always
    build:
      context: .
      dockerfile: ./containers/vernemq/Dockerfile
      args:
        - APP_API_HOST=http://api-gateway.${LOCAL_DOMAIN}:8000
        - APP_API_KEY=${APP_API_KEY}
    networks:
      local-network:
        aliases:
          - vernemq.${LOCAL_DOMAIN}
    ports:
      - 1883:1883
      - 8883:8883
      - 8989:8989

networks:
  local-network:

volumes:
  mariadb_gateway_node_data:
  mariadb_devices_node_data:
  mariadb_triggers_node_data:
  mariadb_accounts_node_data:
  mariadb_ui_node_data:
  couchdb_data: