version: '3.7'

services:
  # API GATEWAY
  api-gateway:
    networks:
      - outside-world
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.api-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.api.entrypoints=http
      - traefik.http.routers.api.rule=Host(`${APP_API_DOMAIN}`)
      - traefik.http.routers.api.middlewares=api-https-redirect
      - traefik.http.routers.api-secure.entrypoints=https
      - traefik.http.routers.api-secure.rule=Host(`${APP_API_DOMAIN}`)
      - traefik.http.routers.api-secure.tls=true
      - traefik.http.routers.api-secure.tls.certresolver=le
      - traefik.http.routers.api-secure.service=api
      - traefik.http.services.api.loadbalancer.server.port=8080
      - traefik.docker.network=traefik-proxy

  # WEB UI NODE
  web-ui-node:
    networks:
      - outside-world
    environment:
      NUXT_ENV_WS_TARGET: wss://${APP_WS_DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ui-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.ui.entrypoints=http
      - traefik.http.routers.ui.rule=Host(`${APP_MASTER_DOMAIN}`)
      - traefik.http.routers.ui.middlewares=ui-https-redirect
      - traefik.http.routers.ui-secure.entrypoints=https
      - traefik.http.routers.ui-secure.rule=Host(`${APP_MASTER_DOMAIN}`)
      - traefik.http.routers.ui-secure.tls=true
      - traefik.http.routers.ui-secure.tls.certresolver=le
      - traefik.http.routers.ui-secure.service=ui
      - traefik.http.services.ui.loadbalancer.server.port=5000
      - traefik.docker.network=traefik-proxy

  # WEBSOCKETS NODE
  websockets-node:
    networks:
      - outside-world
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ws-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.ws.entrypoints=http
      - traefik.http.routers.ws.rule=Host(`${APP_WS_DOMAIN}`)
      - traefik.http.routers.ws.middlewares=ws-https-redirect
      - traefik.http.routers.ws-secure.entrypoints=https
      - traefik.http.routers.ws-secure.rule=Host(`${APP_WS_DOMAIN}`)
      - traefik.http.routers.ws-secure.tls=true
      - traefik.http.routers.ws-secure.tls.certresolver=le
      - traefik.http.routers.ws-secure.service=ws
      - traefik.http.services.ws.loadbalancer.server.port=9878
      - traefik.docker.network=traefik-proxy

networks:
  outside-world:
    external:
      name: traefik-proxy
